// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQ4G0cu-R0MjO90Ib45frl4nMbAdX4lc',
    appId: '1:597608208696:web:3974b4338073cee9ca09cd',
    messagingSenderId: '597608208696',
    projectId: 'pocket-quote',
    authDomain: 'pocket-quote.firebaseapp.com',
    storageBucket: 'pocket-quote.firebasestorage.app',
    measurementId: 'G-Q09VLXMBQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsyiOHH35oE8us2rTgblbc4p5uKFshUsQ',
    appId: '1:597608208696:android:4429631be6ae2829ca09cd',
    messagingSenderId: '597608208696',
    projectId: 'pocket-quote',
    storageBucket: 'pocket-quote.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMRuFYfx6UgWv22c6dXPuV2MbiThLBKz4',
    appId: '1:597608208696:ios:3b69793e5f68a21dca09cd',
    messagingSenderId: '597608208696',
    projectId: 'pocket-quote',
    storageBucket: 'pocket-quote.firebasestorage.app',
    iosBundleId: 'com.bakkiebrigade.quickQuote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMRuFYfx6UgWv22c6dXPuV2MbiThLBKz4',
    appId: '1:597608208696:ios:838da47087089fbfca09cd',
    messagingSenderId: '597608208696',
    projectId: 'pocket-quote',
    storageBucket: 'pocket-quote.firebasestorage.app',
    iosBundleId: 'com.kree8designs.pocketquote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhQ4G0cu-R0MjO90Ib45frl4nMbAdX4lc',
    appId: '1:597608208696:web:80ffdaa3e4997712ca09cd',
    messagingSenderId: '597608208696',
    projectId: 'pocket-quote',
    authDomain: 'pocket-quote.firebaseapp.com',
    storageBucket: 'pocket-quote.firebasestorage.app',
    measurementId: 'G-98T7QC4D50',
  );
}
